### ISSUE TITLE
variable _merge already defined

### ISSUE THREAD

**Issue by socapal** [AzaelMateo/ENOE-ENOE_N#1]
Hola, Azael. 
Espero que estés bien.
Al ejecutar los archivos encuentro dos problemas:

1. Para el primer trimestre de 2020 el archivo falla en extraer la carpeta de datos. Lo realicé manualmente y no hubo problema.
2. Al ejecutar el tercer dofile (Bases Globales) arroja un error porque la variable merge ya está definida. Intentaré corregir el error en el código y cierro el issue si encuentro la solución.  Me parece que están entrandoo en conflicto los dos merge que están en las líneas 40 y 45.

![image](https://user-images.githubusercontent.com/68121592/198363070-093c6dc2-30c3-4601-878f-a15ca6367fa5.png)

**Comment by AzaelMateo** [comment]
Hola Sebas!

1. Por favor indícame en qué parte y de cuál código falla la extracción de datos.
2. Dentro del chunk _2.1_ existen dos líneas inhabilitadas que se encuentran después de cada merge. Estas deberán ser habilitadas para conservar las variables con las que seguirás trabajando y al mismo tiempo desechar las otras que no, como las _merge_ que causan la problemática. 

Saludos amigo!

**Comment by socapal** [comment]
Muchas gracias. Ya con tu comentario pude resolver el problema. 
Creo que también tenía un problema local para descargar la base, pero fue sencillo de solucionar.
Gracias por el código!
